name: Publish package to the Maven Central Repository
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Publish package
        run: mvn --batch-mode verify
